### ISSUE TITLE
observer.observe function can fail if element doesn't exist yet

### ISSUE THREAD

**Issue by mapomatic** [justins83/WazeWrap#2]
![image](https://user-images.githubusercontent.com/19505091/32330742-6832820a-bfb7-11e7-8519-b9b4c9a6da6d.png)

This was captured by Xb.  He said after disabling WME Extras (which no longer works), this error appears to have gone away.  Not sure if it's related or coincidence.  Either way, might not hurt to check for existence of elements before running observe() on them.

**Comment by justins83** [comment]
Yeah, this is due to removing an observer that is no longer necessary and
me missing the actual call to start the MO. I forgot to update beta when I
fixed this in production.

**Comment by mapomatic** [comment]
Oh, derp.  I misunderstood the error.

**Comment by mapomatic** [comment]
Closing this, as it's not even a WazeWrap error
